### ISSUE TITLE
Invalid Inertia when loading a URDF

### ISSUE THREAD

**Issue by aditya-shirwatkar** [gazebosim/ros_gz#155]
## Environment
* OS Version: `Ubuntu 18.04`
* Ignition Release: `Fortress` (binary)
* ROS1: `Melodic`
* Binary build: `version 0.9.5`
  
```
[Msg] Ignition Gazebo Server v6.0.0~pre1
[Msg] Ignition Gazebo GUI    v6.0.0~pre1
[Msg] Loading SDF world file[/home/hubble-02/stochlite/src/stochlite_ros/stochlite_gazebo/worlds/flat.sdf].
[Msg] Loaded level [3]
[Msg] No systems loaded from SDF, loading defaults
[Msg] Create service on [/world/flat/create]
[Msg] Remove service on [/world/flat/remove]
[Msg] Pose service on [/world/flat/set_pose]
[Msg] Light configuration service on [/world/flat/light_config]
[Msg] Physics service on [/world/flat/set_physics]
[Msg] Serving world controls on [/world/flat/control] and [/world/flat/playback/control]
[Msg] Serving GUI information on [/world/flat/gui/info]
[Msg] World [flat] initialized with [default_physics] physics profile.
[Msg] Serving world SDF generation service on [/world/flat/generate_world_sdf]
[Msg] Serving world names on [/gazebo/worlds]
[Msg] Resource path add service on [/gazebo/resource_paths/add].
[Msg] Resource path get service on [/gazebo/resource_paths/get].
[Msg] Resource paths published on [/gazebo/resource_paths].
[INFO] [1622050945.025013]: Controller Spawner: Waiting for service controller_manager/load_controller
[ INFO] [1622050945.098393860]: Requested creation of entity.
[stochlite/create-7] process has finished cleanly
log file: /home/hubble-02/.ros/log/bacf86ae-be49-11eb-8e3e-9c2976c9ae3c/stochlite-create-7*.log
[GUI] [Msg] Loading config [/home/hubble-02/.ignition/gazebo/gui.config]
[GUI] [Msg] Video recorder stats topic advertised on [/gui/record_video/stats]
[GUI] [Msg] Transform mode service on [/gui/transform_mode]
[GUI] [Msg] Record video service on [/gui/record_video]
[GUI] [Msg] Move to service on [/gui/move_to]
[GUI] [Msg] Follow service on [/gui/follow]
[GUI] [Msg] View angle service on [/gui/view_angle]
[GUI] [Msg] Move to pose service on [/gui/move_to/pose]
[GUI] [Msg] Camera pose topic advertised on [/gui/camera/pose]
[GUI] [Msg] View wireframes service on [/gui/view/wireframes]
[GUI] [Msg] View collisions service on [/gui/view/collisions]
[GUI] [Msg] Camera view controller topic advertised on [/gui/camera/view_control]
[GUI] [Msg] Added plugin [3D View] to main window
[GUI] [Msg] Loaded plugin [GzScene3D] from path [/usr/lib/x86_64-linux-gnu/ign-gazebo-6/plugins/gui/libGzScene3D.so]
[GUI] [Msg] Using world control service [/world/flat/control]
[GUI] [Msg] Listening to stats on [/world/flat/stats]
[GUI] [Msg] Added plugin [World control] to main window
[GUI] [Msg] Loaded plugin [WorldControl] from path [/usr/lib/x86_64-linux-gnu/ign-gui-6/plugins/libWorldControl.so]
[GUI] [Msg] Listening to stats on [/world/flat/stats]
[GUI] [Msg] Added plugin [World stats] to main window
[GUI] [Msg] Loaded plugin [WorldStats] from path [/usr/lib/x86_64-linux-gnu/ign-gui-6/plugins/libWorldStats.so]
[GUI] [Msg] Added plugin [Shapes] to main window
[GUI] [Msg] Loaded plugin [Shapes] from path [/usr/lib/x86_64-linux-gnu/ign-gazebo-6/plugins/gui/libShapes.so]
[GUI] [Msg] Added plugin [Lights] to main window
[GUI] [Msg] Loaded plugin [Lights] from path [/usr/lib/x86_64-linux-gnu/ign-gazebo-6/plugins/gui/libLights.so]
[GUI] [Msg] Added plugin [Transform control] to main window
[GUI] [Msg] Loaded plugin [TransformControl] from path [/usr/lib/x86_64-linux-gnu/ign-gazebo-6/plugins/gui/libTransformControl.so]
[GUI] [Msg] Screenshot service on [/gui/screenshot]
[GUI] [Msg] Added plugin [Screenshot] to main window
[GUI] [Msg] Loaded plugin [Screenshot] from path [/usr/lib/x86_64-linux-gnu/ign-gui-6/plugins/libScreenshot.so]
[GUI] [Msg] Added plugin [Component inspector] to main window
[GUI] [Msg] Loaded plugin [ComponentInspector] from path [/usr/lib/x86_64-linux-gnu/ign-gazebo-6/plugins/gui/libComponentInspector.so]
[GUI] [Msg] Added plugin [Entity tree] to main window
[GUI] [Msg] Loaded plugin [EntityTree] from path [/usr/lib/x86_64-linux-gnu/ign-gazebo-6/plugins/gui/libEntityTree.so]
[Wrn] [SimulationRunner.cc:643] Found additional publishers on /stats, using namespaced stats topic only
[Wrn] [SimulationRunner.cc:676] Found additional publishers on /clock, using namespaced clock topic only
[GUI] [Msg] Loading plugin [ignition-rendering-ogre2]
[Err] [UserCommands.cc:602] Error Code 18: [:L-1131947072]: Msg: A link named bl_abd_link has invalid inertia.
[Err] [UserCommands.cc:602] Error Code 18: [:L-1131947040]: Msg: A link named bl_thigh_link has invalid inertia.
[Err] [UserCommands.cc:602] Error Code 18: [:L-1131947008]: Msg: A link named bl_shank_link has invalid inertia.
[Err] [UserCommands.cc:602] Error Code 18: [:L-1131946976]: Msg: A link named br_abd_link has invalid inertia.
[Err] [UserCommands.cc:602] Error Code 18: [:L-1131946944]: Msg: A link named br_thigh_link has invalid inertia.
[Err] [UserCommands.cc:602] Error Code 18: [:L-1131946912]: Msg: A link named br_shank_link has invalid inertia.
[Err] [UserCommands.cc:602] Error Code 18: [:L-1131946880]: Msg: A link named fl_abd_link has invalid inertia.
[Err] [UserCommands.cc:602] Error Code 18: [:L-1131946848]: Msg: A link named fl_thigh_link has invalid inertia.
[Err] [UserCommands.cc:602] Error Code 18: [:L-1131946816]: Msg: A link named fl_shank_link has invalid inertia.
[Err] [UserCommands.cc:602] Error Code 18: [:L-1131946784]: Msg: A link named fr_abd_link has invalid inertia.
[Err] [UserCommands.cc:602] Error Code 18: [:L-1131946752]: Msg: A link named fr_thigh_link has invalid inertia.
[Err] [UserCommands.cc:602] Error Code 18: [:L-1131946720]: Msg: A link named fr_shank_link has invalid inertia.
/usr/lib/ruby/ignition/cmdgazebo6.rb:431: [BUG] Segmentation fault at 0x00007f00a31b0720
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

-- Control frame information -----------------------------------------------
c:0007 p:---- s:0076 e:000075 CFUNC  :call
c:0006 p:0017 s:0054 e:000053 METHOD /usr/lib/ruby/ignition/cmdgazebo6.rb:431
c:0005 p:0160 s:0048 e:000047 BLOCK  /usr/lib/ruby/ignition/cmdgazebo6.rb:460 [FINISH]
c:0004 p:---- s:0045 e:000044 CFUNC  :fork
c:0003 p:0675 s:0041 e:000040 METHOD /usr/lib/ruby/ignition/cmdgazebo6.rb:456
c:0002 p:0695 s:0020 E:001900 EVAL   /usr/bin/ign:275 [FINISH]
c:0001 p:0000 s:0003 E:000210 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/usr/bin/ign:275:in `<main>'
/usr/lib/ruby/ignition/cmdgazebo6.rb:456:in `execute'
/usr/lib/ruby/ignition/cmdgazebo6.rb:456:in `fork'
/usr/lib/ruby/ignition/cmdgazebo6.rb:460:in `block in execute'
/usr/lib/ruby/ignition/cmdgazebo6.rb:431:in `runServer'
/usr/lib/ruby/ignition/cmdgazebo6.rb:431:in `call'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f00a31b0720 RBP: 0x000055bcbc87dd40 RSP: 0x00007ffe6adf78a8
 RAX: 0x0000000000000000 RBX: 0x000055bcbc87dbc0 RCX: 0x0000000000000003
 RDX: 0x000055bcba908010 RDI: 0x000055bcbc8dbd90 RSI: 0x000055bcba908040
  R8: 0x000055bcbc87d0d0  R9: 0x0000000000000008 R10: 0x0000000000000200
 R11: 0x0000000000000000 R12: 0x00007ffe6adf7930 R13: 0x000055bcbc87dd40
 R14: 0x0000000000000000 R15: 0x00007ffe6adf7920 EFL: 0x0000000000010206

-- C level backtrace information -------------------------------------------
[GUI] [Msg] Loading plugin [ignition-rendering-ogre2]
================================================================================REQUIRED process [ign_gazebo-2] has died!
process has finished cleanly
log file: /home/hubble-02/.ros/log/bacf86ae-be49-11eb-8e3e-9c2976c9ae3c/ign_gazebo-2*.log
Initiating shutdown!
================================================================================
[stochlite/stochlite_gazebo-6] killing on exit
[stochlite/linear_policy_controller-5] killing on exit
[stochlite/controller_spawner-4] killing on exit
[stochlite/robot_state_publisher-3] killing on exit
[ign_gazebo-2] killing on exit
[WARN] [1622050946.497910]: Controller Spawner couldn't find the expected controller_manager ROS interface.
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

## Description
* Expected behavior: The URDF to be loaded normally (works with Gazebo Classic)
* Actual behavior: Invalid Inertia of links

This is what I'm doing to spawn the robot ("stochlite" is the name of my robot)

```xml
<node pkg="ros_ign_gazebo" type="create" name="create" output="screen" 
args="-world $(arg gazebo_world) -file $(find stochlite_description)/urdf/stochlite.urdf -name spawned 
-x $(arg world_init_x) -y $(arg world_init_y) -z $(arg world_init_z) -Y $(arg world_init_heading) -R $(arg world_init_ang)">
</node>
```
The world file is loading properly (tried it without the model), So I doubt it's an issue on that front.

## Steps to reproduce

The behavior also happens with the sphere sdf example given in this repo (again, works with Gazebo Classic)
1. Inside the sphere.sdf in the demo folder replace the interial parameters with below
```  
<mass value="0.037"/>
<inertia ixx="0.00043261" ixy="-0.00067195" ixz="3.147E-05" iyy="0.0010929" iyz="-1.979E-05" izz="0.0051879"/>
```

## Output

Inertia parameters of one of the links (which work perfectly fine with URDF spawner of Gazebo classic)
![image](https://user-images.githubusercontent.com/50446525/119707336-acd62380-be78-11eb-9394-5c90697c2d4f.png)

**Comment by chapulina** [comment]
> work perfectly fine with URDF spawner of Gazebo classic

Ignition Gazebo is a bit more strict when loading a model to help users detect errors in their simulations quickly. I can see you have a couple of negative inertia values, which is not valid and should result in malformed simulations.

See the [mass matrix documentation](https://ignitionrobotics.org/api/math/6.8/classignition_1_1math_1_1MassMatrix3.html#adb32eb01989f4395bd33407b08afcd7a) for more information.

I'll close this ticket since it isn't a bug on Ignition, but please reopen if you notice something different.
